POST http://localhost:4000/user/login
Content-Type: application/json

{
	"email": "krishna@golok.om",
	"password": "radhakrishna"
}


###
POST http://localhost:4000/register
Content-Type: application/json

{
	"email": "krishna@golok.om",
	"name": "krishna",
	"password": "radhakrishna",
	"gender": "male",
	"location": "vrindavan",
    "mobile":8888888888
}

###
GET http://localhost:4000/user/sendotp

###
POST http://localhost:4000/user/verifyotp
Content-Type: application/json

{
	"UserEmail":"prakashdumpa143@gmail.com",
	"receivedOtp":"687474"
}